### ISSUE TITLE
emitting more than 3 arguments and using onAny will result in arguments[0] being undefined

### ISSUE THREAD

**Issue by MatsN** [asyncly/EventEmitter2#170]
eventemitter2.js line 284: for (j = 1; j < al; j++) args[j] = arguments[j];   //j should start from 0 here 

eventemitter2.js line 300:  handler[i].apply(this, args); // args[0] will be undefined here

**Comment by RangerMauve** [comment]
Thanks for the report. It seems that the intention was to skip the first argument, since that is the event name. But it should have been filling up the args array from `j - 1` since that should start from index 0. I'll see if I can devote some time later this week. A PR with a fix would be appreciated in the meantime.

**Comment by RangerMauve** [comment]
Closed via #175
