### ISSUE TITLE
Wildcards don't work if part of an exported module

### ISSUE THREAD

**Issue by Grayda** [asyncly/EventEmitter2#186]
I'm writing an app using [Cloud9's Architect](https://github.com/c9/architect) plugin system, and want to use EventEmitter2 because wildcards are awesome.

On its own, EE2 wildcards work great, but as soon as I wrap them up in a module, wildcards stop working.

Here's some sample code:

In a file called `ee.js`:
```
var EventEmitter2 = require("eventemitter2").EventEmitter2
var emitter = new EventEmitter2({
  wildcard: true
})
module.exports = {
  emit: emitter.emit,
  on: emitter.on,
}
```

In a file called `test.js`:

```
var ee = require("./ee.js")

ee.on("**", function() {
  console.log("An event was emitted: " + this.event)
})

ee.on("test.*", function() {
  console.log(this.event + " in the test namespace was called")
})

ee.on("test.abc", function() {
  console.log("test.abc was called, but not detected via wildcard")
})

ee.emit("hello.world")
ee.emit("test.abc")
ee.emit("hello.abc.def")
```

The output is:

> C:\Users\grayda\Documents\GitHub\sample>node test.js
> test.abc was called, but not detected via wildcard

When the expected output should be:

> C:\Users\grayda\Documents\GitHub\sample>node test.js
> An event was emitted: hello.world
> test.abc was called, but not detected via wildcard
> test.abc in the test namespace was called
> An event was emitted: test.abc
> An event was emitted: hello.abc.def

Any clues as to what's going on?

**Comment by RangerMauve** [comment]
The main problem is that when you're calling `exports.emit`, the `this` value inside the function is getting set to `exports` rather than `emitter`. This means that when it tries to call `this._events` inside `emit`, it'll actually be calling `exports._events` which will be undefined at first.

The easiest way to fix it is by calling [.bind](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_objects/Function/bind) on the functions.

```javascript
module.exports = {
 emit: emitter.emit.bind(emitter),
 on: emitter.on.bind(emitter)
};
```

This will ensure that the `this` value is preserved.

**Comment by Grayda** [comment]
I thought that was the case, but wasn't sure of the best way to approach it.

The code works beautifully now. Thanks!
